routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



/*
	LAYOUTS
*/
Route::get('compact',function(){
	session(['layout' => 'compact']);
	return back();
})->name('compact');

Route::get('horizontal',function(){
	session(['layout' => 'compact']);
	return back();
})->name('horizontal');

Route::get('normal',function(){
	session(['layout' => 'normal']);
	return back();
})->name('normal');

Route::get('horizontal',function(){
	session(['layout' => 'horizontal']);
	return back();
})->name('horizontal');

Route::get('color-blue',function(){
	session(['color' => 'blue']);
	return back();
})->name('blue');

Route::get('color-purple',function(){
	session(['color' => 'purple']);
	return back();
})->name('purple');



//LAYOUTS
//Backend
Auth::routes();

Route::get('/','Backend\DashboardController@showDash')->name('home');
Route::prefix('dashboard')->group(function(){
	Route::get('/','Backend\DashboardController@showDash')->name('dashboard');
	Route::get('get-schedules','Backend\DashboardController@loadAssistance');
});


//modules
Route::resource('modules','Backend\ModuleController',['except'=>['show']]);
//Permisos
Route::resource('permissions','Backend\PermissionController',['except'=>['show']]);
//Tipos de Permisos
Route::resource('permission-types','Backend\PermissionTypeController',['except'=>['show']]);
//Roles
Route::resource('roles','Backend\RoleController',['except'=>['show']]);

//Person Type
Route::resource('ptypes','Backend\PersonTypeController',['except'=>['show']]);

//Users
Route::post('users/representants','Backend\UserController@searchRepresentant')->name('users.representants');
Route::resource('users','Backend\UserController',['except'=>['show']]);

//Fields
Route::get('fields/{fieldId}/schedule','Backend\FieldController@getSchedule');
Route::resource('fields','Backend\FieldController');

//ftypes
Route::resource('ftypes','Backend\FieldTypeController',['except'=>['show']]);

//Student
Route::resource('students','Backend\StudentController',['except'=>['show']]);

//Age Ranges
Route::resource('ageranges','Backend\AgeRangeController',['except'=>['show']]);

//Groups Class
Route::resource('groupclass','Backend\GroupClassController',['except'=>['show']]);
Route::resource('fields.groupclass','Backend\GroupClassController',['except'=>['show']]);
Route::post('groupclass/remove-all','Backend\GroupClassController@removeAllGroupsBySchedule');

//seasons
Route::get('seasons/get-current-duration-season','Backend\SeasonController@getDurationSeason');
Route::resource('seasons','Backend\SeasonController',['except'=>['show']]);

//Assitance
Route::resource('assistances','Backend\AssistanceController',['except'=>['show','create','edit','update']]);

//Coachs
Route::resource('coachs','Backend\CoachController',['except' => ['show']]);
Route::get('coachs-assistances/schedule','Backend\AssistanceCoachController@loadDaysMonth');
Route::resource('coachs-assistances','Backend\AssistanceCoachController',['only'=>['index','store','update']]);

app/Http/Controllers/Backend/AgeRangeController.php
<?php

namespace Futbol\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Futbol\Http\Controllers\Controller;
use Futbol\Http\Requests\AgeRangeRequest;
use Futbol\RepositoryInterface\AgeRangeRepositoryInterface;
use Futbol\Exceptions\AgeRangeException;


class AgeRangeController extends Controller
{
    

    protected $ageRange;

    protected $routeRedirectIndex = 'ageranges.index';


    public function __construct(AgeRangeRepositoryInterface $ageRange)
    {
        $this->middleware('auth');
        $this->ageRange = $ageRange;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $ageRanges = $this->ageRange->enum();
        return view('backend.agerange.index',compact('ageRanges'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.agerange.create-edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AgeRangeRequest $request)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];

        try {
            $message['content'] = "Se ha creado el rango de edad satisfactoriamente";
            $ageRange = $this->ageRange->save($request->all());
            if ($request->get('redirect-index') == 1) {
                return redirect()->route($this->routeRedirectIndex)->with($message);
            } else {
                return redirect()->route('ageranges.edit',['id'=>$ageRange->id])->with($message);
            }
        } catch (AgeRangeException $e) {
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }
            
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $agerange = $this->ageRange->find($id);
        return view('backend.agerange.create-edit',compact('agerange'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];
        try {
          $ageRange = $this->ageRange->edit($id,$request->all());
          $message['content'] = "Se ha Actualizado el rango de edad satisfactoriamente";
          
          if ($request->get('redirect-index') == 1) { 
            return redirect()->route($this->routeRedirectIndex)->with($message);
          } else {
            return back()->with($message);
          }
          
        } catch (AgeRangeException $e) {
            $message['type'] = 'error';
            $message['content'] = $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];
        try {
            $deleted = $this->ageRange->remove($id);
            $message['content'] = "Se ha eliminado el rango de edad satisfactoriamente";
            return back()->with($message);
        } catch (AgeRangeException $e) {
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }
        
    }
}

app/Http/Controllers/Backend/AssistanceCoachController.php
<?php

namespace Futbol\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Futbol\Http\Controllers\Controller;
use Futbol\RepositoryInterface\AssistanceCoachRepositoryInterface;
use Futbol\RepositoryInterface\FieldRepositoryInterface;
use Futbol\RepositoryInterface\CoachRepositoryInterface;
use Futbol\Http\Requests\AssistanceCoachRequest;
use Futbol\Exceptions\AssistanceCoachException;
use DB;

class AssistanceCoachController extends Controller
{
    
    protected $assistance;
    protected $coach;
    protected $field;
    
    protected $routeRedirectIndex = 'assistances.index';


    function __construct(AssistanceCoachRepositoryInterface $assistance, CoachRepositoryInterface $coach, FieldRepositoryInterface $field)
    {
        $this->middleware('auth');
        $this->assistance = $assistance;
        $this->coach = $coach;
        $this->field = $field;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $coachs = $this->coach->enum();
        $fields = $this->field->enum();
        return view('backend.assistance-coach.index', compact('fields','coachs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.assistance.create-edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AssistanceCoachRequest $request)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];
        //begin transaction
        DB::beginTransaction();
        try {
            $message['content'] = "Se han guardado la asistencia Satisfactoriamente";
            $assistance = $this->assistance->save($request->all());
            DB::commit();
            return back()->with($message);
        } catch (AssistanceCoachException $e) {
            DB::rollback();
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        } catch (Exception $e) {
            DB::rollback();
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id, Request $request)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $assistance = $this->assistance->find($id);
        $aRanges = $this->ageRange->enum();
        $daysOfWeek = days_of_week();
        return view('backend.assistance.create-edit',compact('assistance','daysOfWeek','aRanges'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AssistanceCoachRequest $request, $id)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];
        try {
            $assistance = $this->assistance->edit($id,$request->all());
            $message['content'] = "Se ha Actualizado la asistencia satisfactoriamente";
            
          if ($request->get('redirect-index') == 1) { 
            return redirect()->route($this->routeRedirectIndex)->with($message);
          } else {
            return back()->with($message);
          }
          
        } catch (AssistanceCoachException $e) {
            $message['type'] = 'error';
            $message['content'] = $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];
        try {
            $deleted = $this->assistance->remove($id);
            $message['content'] = "Se ha eliminado la cancha satisfactoriamente";
            return back()->with($message);
        } catch (AssistanceCoachException $e) {
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }
    }


    public function loadDaysMonth(Request $request)
    {
        try {
           if ($request->ajax()) {
                $monthSelected = $request->get('month');
                $fieldId = $request->get('field');
                $coachsId = $request->get('coachs');
                $days = $this->assistance->loadDaysMonth($monthSelected,$fieldId, $coachsId);
                return response($days,200);
           } 
        } catch (Exception $e) {
            
        }
    }
}

app/Http/Controllers/Backend/CoachController.php
<?php

namespace Futbol\Http\Controllers\Backend;

use Futbol\Http\Controllers\Controller;
use Futbol\RepositoryInterface\CoachRepositoryInterface;
use Futbol\Http\Requests\CoachRequest;
use Futbol\Exception\CoachException;
use DB;

class CoachController extends Controller
{
    
    protected $coachRepo;
    protected $seasonRepo;
    protected $fieldRepo;

    protected $routeRedirectIndex = 'coachs.index';

    function __construct(CoachRepositoryInterface $coachRepo)
    {
        $this->middleware('auth');
        $this->coachRepo = $coachRepo;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $coachs = $this->coachRepo->enum();
        return view('backend.coach.index',compact('coachs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.coach.create-edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CoachRequest $request)
    {
       $message = [
            'type' => 'success',
            'content' =>'',
        ];
        
        DB::beginTransaction();
        try {
            $message['content'] = "Se ha creado el coach satisfactoriamente";
            $coach = $this->coachRepo->save($request->all());
            DB::commit();
            if ($request->get('redirect-index') == 1) {
                return redirect()->route($this->routeRedirectIndex)->with($message);
            } else {
                return redirect()->route('coachs.edit',['id'=>$coach->id])->with($message);
            }
        } catch (CoachException $e) {
            DB::rollback();
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        } catch (Exception $e) {
            DB::rollback();
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $coach = $this->coachRepo->find($id);
        return view('backend.coach.create-edit',compact('coach'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CoachRequest $request, $id)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];
        DB::beginTransaction();
        
        try {
            $coach = $this->coachRepo->edit($id,$request->all());
            DB::commit();
            $message['content'] = "Se ha Actualizado el coach satisfactoriamente";
          
              if ($request->get('redirect-index') == 1) { 
                return redirect()->route($this->routeRedirectIndex)->with($message);
              } else {
                return back()->with($message);
              }
          
        } catch (CoachException $e) {
            DB::rollback();
            $message['type'] = 'error';
            $message['content'] = $e->getMessage();
        }catch (Exception $e) {
            DB::rollback();
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];
         DB::beginTransaction();

        try {
            $deleted = $this->coachRepo->remove($id);
            DB::commit();
            $message['content'] = "Se ha eliminado el coach satisfactoriamente";
            return back()->with($message);
        } catch (CoachException $e) {
            DB::rollback();
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }catch (Exception $e) {
            DB::rollback();
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }
    }
}

resources/views/backend/ftype/create-edit.blade.php
@extends('layouts.backend')
@section('title', isset($ftype) ?  'Editar Tipo de Cancha '. $ftype->name : 'Crear Tipo de Cancha' )
@section('parent-page','Tipos de Cancha')
@section('route-parent',route('ftypes.index') )
@section('current-page', isset($ftype) ?  'Editar Tipo de Cancha '. $ftype->name : 'Crear Tipo de Cancha' )

@section('content')
<!-- Start Page Content -->
<div class="row">
    <div class="col-12">
		<ul class="nav nav-tabs customtab">
            <li class="nav-item">
                <a class="nav-link" id="field-tab" href="{{route('fields.index')}}">Canchas</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link active"  id="range-age-tab"  data-toggle="tab" href="#ageranges" role="tab" aria-controls="ageranges" aria-selected="true"> Tipos de Cancha</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" id="range-age-tab"  href="{{route('ageranges.index')}}">Rango de Edades</a>
            </li>

        </ul>

        <div class="card">
    		<div class="card-body">
    			@if (session()->has('type') && session()->has('content'))
            		<div class="alert alert-card alert-{{ session()->get('type') }} sufee-alert alert with-close alert-dismissible fade show">
            			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            			{{ session()->get('content') }}
            		</div>
    			@endif

				<form action="@if(isset($ftype)) {{ route('ftypes.update',['id'=>$ftype->id]) }} @else {{ route('ftypes.store') }} @endif" method="POST" class="crud-futbol">
            		{{ csrf_field() }}
            		@if (isset($ftype))
            			<input type="hidden" name="_method" value="PUT">
            			<input type="hidden" name="key" value="{{ $ftype->id }}">
            		@endif
                	<div class="row">
                		<div class="col-lg-4 col-6">
	                		<div class="form-group">
	                			<label for="name">Nombre <span class="text-danger">*</span></label>
	                			<input type="text" name="name" id="name" class="form-control {{ $errors->has('name') ? ' is-invalid' : '' }}"  autofocus="" value="@if(isset($ftype)){{ $ftype->name }}@else{{ old('name') }}@endif">
	                			@if ($errors->has('name'))
	                				<div class="invalid-feedback animated fadeInDown">{{ $errors->first('name') }}</div>
	                			@endif
	                		</div>
                		</div>
                	</div>
			
    		</div>
    		<div class="card-footer">
		    	<div class="form-actions">
		    		<input type="hidden" value="0" name="redirect-index" id="redirect-index">
		    		<button class="btn btn-primary " type="submit"><i class="i-Data-Save"></i> Guardar</button>
		    		<button class="btn btn-secondary  save-close" type="submit"><i class="i-Data-Save"></i> Guardar y Cerrar</button>
		    		<a class="btn btn-dark" href="{{ route('ftypes.index') }}"><i class="i-Arrow-Back-2"></i> Cancelar</a>
		    	</div>
    			</form>	
    		</div>
        </div>
    </div>
</div>
@endsection

resources/views/backend/ftype/index.blade.php
@extends('layouts.backend')
@section('title','Tipos de Cancha')
@section('parent-page','Escritorio')
@section('route-parent',route('home'))
@section('current-page','Tipos de Cancha')

@section('js')
<script type="text/javascript" src="{{ asset('js/data-table/datatables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/components/ftype.js') }}"></script>
@endsection

@section('css')
<link rel="stylesheet" href="{{ asset('css/data-table/datatables.min.css') }}">
@endsection

@section('content')
<ul class="nav nav-tabs customtab">
    <li class="nav-item">
        <a class="nav-link" id="field-tab" href="{{route('fields.index')}}">Canchas</a>
    </li>
    
    <li class="nav-item">
        <a class="nav-link active"  id="range-age-tab"  data-toggle="tab" href="#ageranges" role="tab" aria-controls="ageranges" aria-selected="true"> Tipos de Cancha</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" id="range-age-tab"  href="{{route('ageranges.index')}}">Rango de Edades</a>
    </li>

</ul>

<div class="car">

    <div class="row">
        <div class="card-title col-6 mt-4 ml-4">
            <h3>Listado</h3>
        </div>
        <div class="col-5 mt-4 ml-4 text-right">
            <a href="{{ route('ftypes.create') }}" class="btn btn-primary "><i class="i-Add"></i> Crear</a>             
        </div>
    </div>

    <div class="card-body">
        @if (session()->has('type') && session()->has('content'))
            <div class="alert alert-card alert-{{ session()->get('type') }} sufee-alert alert with-close alert-dismissible fade show">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                {{ session()->get('content') }}
            </div>
        @endif

        {{-- validation errors --}}
        @if($errors->any())
            <div class="alert alert-card alert-danger sufee-alert alert with-close alert-dismissible fade show">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                <ul class="mb-0">
                    @foreach ($errors->all() as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <table class="table table-hover table-responsive-lg" id="list-ftypes">
    		<thead>
    			<tr>
                    <th>Nombre</th>
    				<th>Acción</th>
    			</tr>
    		</thead>
    		<tbody>
				@foreach ($fieldTypes as $ftype)
    			<tr>
                    <td><a href="{{ route('ftypes.edit',['id' => $ftype->id]) }}" class="text-primary">{{ $ftype->name }}</a></td>
    				<td>
    					<a class="btn btn-warning btn-flat " href="{{ route('ftypes.edit',['id' => $ftype->id]) }}"><i class="i-Pen-2"></i> Editar</a>
    					<button class="btn btn-danger btn-flat  delete-btn text-light" data-toggle="modal" data-target="#delete-modal" data-object="{{$ftype}}" data-message="Está seguro de eliminar el Tipo de " data-route="{{ route('ftypes.destroy',$ftype->id) }}"><i class="i-File-Trash"></i> Eliminar</button>
    				</td>
    			</tr>
    			@endforeach
    		</tbody>
    	</table>
    </div>
</div>
@endsection