routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



/*
	LAYOUTS
*/
Route::get('compact',function(){
	session(['layout' => 'compact']);
	return back();
})->name('compact');

Route::get('horizontal',function(){
	session(['layout' => 'compact']);
	return back();
})->name('horizontal');

Route::get('normal',function(){
	session(['layout' => 'normal']);
	return back();
})->name('normal');

Route::get('horizontal',function(){
	session(['layout' => 'horizontal']);
	return back();
})->name('horizontal');

Route::get('color-blue',function(){
	session(['color' => 'blue']);
	return back();
})->name('blue');

Route::get('color-purple',function(){
	session(['color' => 'purple']);
	return back();
})->name('purple');



//LAYOUTS
//Backend
Auth::routes();

Route::get('/','Backend\DashboardController@showDash')->name('home');
Route::prefix('dashboard')->group(function(){
	Route::get('/','Backend\DashboardController@showDash')->name('dashboard');
	Route::get('get-schedules','Backend\DashboardController@loadAssistance');
});


//modules
Route::resource('modules','Backend\ModuleController',['except'=>['show']]);
//Permisos
Route::resource('permissions','Backend\PermissionController',['except'=>['show']]);
//Tipos de Permisos
Route::resource('permission-types','Backend\PermissionTypeController',['except'=>['show']]);
//Roles
Route::resource('roles','Backend\RoleController',['except'=>['show']]);

//Person Type
Route::resource('ptypes','Backend\PersonTypeController',['except'=>['show']]);

//Users
Route::post('users/representants','Backend\UserController@searchRepresentant')->name('users.representants');
Route::resource('users','Backend\UserController',['except'=>['show']]);

//Fields
Route::get('fields/{fieldId}/schedule','Backend\FieldController@getSchedule');
Route::resource('fields','Backend\FieldController');

//ftypes
Route::resource('ftypes','Backend\FieldTypeController',['except'=>['show']]);

//Student
Route::resource('students','Backend\StudentController',['except'=>['show']]);

//Age Ranges
Route::resource('ageranges','Backend\AgeRangeController',['except'=>['show']]);

//Groups Class
Route::resource('groupclass','Backend\GroupClassController',['except'=>['show']]);
Route::resource('fields.groupclass','Backend\GroupClassController',['except'=>['show']]);
Route::post('groupclass/remove-all','Backend\GroupClassController@removeAllGroupsBySchedule');

//seasons
Route::get('seasons/get-current-duration-season','Backend\SeasonController@getDurationSeason');
Route::resource('seasons','Backend\SeasonController',['except'=>['show']]);

//Assitance
Route::resource('assistances','Backend\AssistanceController',['except'=>['show','create','edit','update']]);

//Coachs
Route::resource('coachs','Backend\CoachController',['except' => ['show']]);
Route::get('coachs-assistances/schedule','Backend\AssistanceCoachController@loadDaysMonth');
Route::resource('coachs-assistances','Backend\AssistanceCoachController',['only'=>['index','store','update']]);

app/Http/Controllers/Backend/AgeRangeController.php
<?php

namespace Futbol\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Futbol\Http\Controllers\Controller;
use Futbol\Http\Requests\AgeRangeRequest;
use Futbol\RepositoryInterface\AgeRangeRepositoryInterface;
use Futbol\Exceptions\AgeRangeException;


class AgeRangeController extends Controller
{
    

    protected $ageRange;

    protected $routeRedirectIndex = 'ageranges.index';


    public function __construct(AgeRangeRepositoryInterface $ageRange)
    {
        $this->middleware('auth');
        $this->ageRange = $ageRange;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $ageRanges = $this->ageRange->enum();
        return view('backend.agerange.index',compact('ageRanges'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.agerange.create-edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AgeRangeRequest $request)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];

        try {
            $message['content'] = "Se ha creado el rango de edad satisfactoriamente";
            $ageRange = $this->ageRange->save($request->all());
            if ($request->get('redirect-index') == 1) {
                return redirect()->route($this->routeRedirectIndex)->with($message);
            } else {
                return redirect()->route('ageranges.edit',['id'=>$ageRange->id])->with($message);
            }
        } catch (AgeRangeException $e) {
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }
            
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $agerange = $this->ageRange->find($id);
        return view('backend.agerange.create-edit',compact('agerange'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];
        try {
          $ageRange = $this->ageRange->edit($id,$request->all());
          $message['content'] = "Se ha Actualizado el rango de edad satisfactoriamente";
          
          if ($request->get('redirect-index') == 1) { 
            return redirect()->route($this->routeRedirectIndex)->with($message);
          } else {
            return back()->with($message);
          }
          
        } catch (AgeRangeException $e) {
            $message['type'] = 'error';
            $message['content'] = $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];
        try {
            $deleted = $this->ageRange->remove($id);
            $message['content'] = "Se ha eliminado el rango de edad satisfactoriamente";
            return back()->with($message);
        } catch (AgeRangeException $e) {
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }
        
    }
}

app/Http/Controllers/Backend/AssistanceCoachController.php
<?php

namespace Futbol\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Futbol\Http\Controllers\Controller;
use Futbol\RepositoryInterface\AssistanceCoachRepositoryInterface;
use Futbol\RepositoryInterface\FieldRepositoryInterface;
use Futbol\RepositoryInterface\CoachRepositoryInterface;
use Futbol\Http\Requests\AssistanceCoachRequest;
use Futbol\Exceptions\AssistanceCoachException;
use DB;

class AssistanceCoachController extends Controller
{
    
    protected $assistance;
    protected $coach;
    protected $field;
    
    protected $routeRedirectIndex = 'assistances.index';


    function __construct(AssistanceCoachRepositoryInterface $assistance, CoachRepositoryInterface $coach, FieldRepositoryInterface $field)
    {
        $this->middleware('auth');
        $this->assistance = $assistance;
        $this->coach = $coach;
        $this->field = $field;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $coachs = $this->coach->enum();
        $fields = $this->field->enum();
        return view('backend.assistance-coach.index', compact('fields','coachs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.assistance.create-edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AssistanceCoachRequest $request)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];
        //begin transaction
        DB::beginTransaction();
        try {
            $message['content'] = "Se han guardado la asistencia Satisfactoriamente";
            $assistance = $this->assistance->save($request->all());
            DB::commit();
            return back()->with($message);
        } catch (AssistanceCoachException $e) {
            DB::rollback();
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        } catch (Exception $e) {
            DB::rollback();
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id, Request $request)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $assistance = $this->assistance->find($id);
        $aRanges = $this->ageRange->enum();
        $daysOfWeek = days_of_week();
        return view('backend.assistance.create-edit',compact('assistance','daysOfWeek','aRanges'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AssistanceCoachRequest $request, $id)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];
        try {
            $assistance = $this->assistance->edit($id,$request->all());
            $message['content'] = "Se ha Actualizado la asistencia satisfactoriamente";
            
          if ($request->get('redirect-index') == 1) { 
            return redirect()->route($this->routeRedirectIndex)->with($message);
          } else {
            return back()->with($message);
          }
          
        } catch (AssistanceCoachException $e) {
            $message['type'] = 'error';
            $message['content'] = $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];
        try {
            $deleted = $this->assistance->remove($id);
            $message['content'] = "Se ha eliminado la cancha satisfactoriamente";
            return back()->with($message);
        } catch (AssistanceCoachException $e) {
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }
    }


    public function loadDaysMonth(Request $request)
    {
        try {
           if ($request->ajax()) {
                $monthSelected = $request->get('month');
                $fieldId = $request->get('field');
                $coachsId = $request->get('coachs');
                $days = $this->assistance->loadDaysMonth($monthSelected,$fieldId, $coachsId);
                return response($days,200);
           } 
        } catch (Exception $e) {
            
        }
    }
}

app/Http/Controllers/Backend/CoachController.php
<?php

namespace Futbol\Http\Controllers\Backend;

use Futbol\Http\Controllers\Controller;
use Futbol\RepositoryInterface\CoachRepositoryInterface;
use Futbol\Http\Requests\CoachRequest;
use Futbol\Exception\CoachException;
use DB;

class CoachController extends Controller
{
    
    protected $coachRepo;
    protected $seasonRepo;
    protected $fieldRepo;

    protected $routeRedirectIndex = 'coachs.index';

    function __construct(CoachRepositoryInterface $coachRepo)
    {
        $this->middleware('auth');
        $this->coachRepo = $coachRepo;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $coachs = $this->coachRepo->enum();
        return view('backend.coach.index',compact('coachs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.coach.create-edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CoachRequest $request)
    {
       $message = [
            'type' => 'success',
            'content' =>'',
        ];
        
        DB::beginTransaction();
        try {
            $message['content'] = "Se ha creado el coach satisfactoriamente";
            $coach = $this->coachRepo->save($request->all());
            DB::commit();
            if ($request->get('redirect-index') == 1) {
                return redirect()->route($this->routeRedirectIndex)->with($message);
            } else {
                return redirect()->route('coachs.edit',['id'=>$coach->id])->with($message);
            }
        } catch (CoachException $e) {
            DB::rollback();
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        } catch (Exception $e) {
            DB::rollback();
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $coach = $this->coachRepo->find($id);
        return view('backend.coach.create-edit',compact('coach'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CoachRequest $request, $id)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];
        DB::beginTransaction();
        
        try {
            $coach = $this->coachRepo->edit($id,$request->all());
            DB::commit();
            $message['content'] = "Se ha Actualizado el coach satisfactoriamente";
          
              if ($request->get('redirect-index') == 1) { 
                return redirect()->route($this->routeRedirectIndex)->with($message);
              } else {
                return back()->with($message);
              }
          
        } catch (CoachException $e) {
            DB::rollback();
            $message['type'] = 'error';
            $message['content'] = $e->getMessage();
        }catch (Exception $e) {
            DB::rollback();
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $message = [
            'type' => 'success',
            'content' =>'',
        ];
         DB::beginTransaction();

        try {
            $deleted = $this->coachRepo->remove($id);
            DB::commit();
            $message['content'] = "Se ha eliminado el coach satisfactoriamente";
            return back()->with($message);
        } catch (CoachException $e) {
            DB::rollback();
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }catch (Exception $e) {
            DB::rollback();
            $message['type'] = "error";
            $message['content'] = $e->getMessage();
            return back()->with($message);
        }
    }
}

resources/views/backend/user/index.blade.php
@extends('layouts.backend')
@section('title','Usuarios')
@section('parent-page','Escritorio')
@section('route-parent',route('home'))
@section('current-page','Usuarios')

@section('js')
<script type="text/javascript" src="{{ asset('js/data-table/datatables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/components/user.js') }}"></script>
@endsection

@section('css')
<link rel="stylesheet" href="{{ asset('css/data-table/datatables.min.css') }}">
@endsection

@section('content')

<ul class="nav nav-tabs customtab">
    <li class="nav-item">
        <a class="nav-link active" id="field-tab" data-toggle="tab" href="#users" role="tab" aria-controls="user" aria-selected="true">Usuarios</a>
    </li>
    
    <li class="nav-item">
        <a class="nav-link" id="roles-tab"  href="{{route('roles.index')}}">Roles</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" id="permissions-tab"  href="{{route('permissions.index')}}">Permisos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="permissionstype-tab"  href="{{route('permission-types.index')}}">Tipos de Permisos</a>
    </li>
</ul>

<div class="card">
    
    <div class="tab-pane fade show active" id="users" role="tabpanel" aria-labelledby="user-tab">
        <div class="row">
            <div class="card-title col-6 mt-4 ml-4">
                <h3>Listado</h3>
            </div>
            <div class="col-5 mt-4 ml-4 text-right">
                <a href="{{ route('users.create') }}" class="btn btn-primary "><i class="i-Add"></i> Crear</a>             
            </div>
        </div>

        <div class="card-body"> 
            @if (session()->has('type') && session()->has('content'))
                <div class="alert alert-card alert-{{ session()->get('type') }}">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                    {{ session()->get('content') }}
                </div>
            @endif

            {{-- validation errors --}}
            @if($errors->any())
                <div class="alert alert-card alert-danger sufee-alert alert with-close alert-dismissible fade show">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <ul class="mb-0">
                        @foreach ($errors->all() as $error)
                            <li>{{$error}}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <table class="table table-hover table-responsive-lg" id="list-users">
        		<thead>
        			<tr>
                        <th>Usuario</th>
                        <th>Nombre</th>
        				<th>Super Admin</th>
        				<th>Último Acceso</th>
        				<th>Acción</th>
        			</tr>
        		</thead>
        		<tbody>
    				@foreach ($users as $user)
        			<tr>
                        <td><a href="{{ route('users.edit',['id' => $user->id]) }}" class="text-primary">{{ $user->username }}</a></td>
                        <td>{{$user->person->name .' '. $user->person->last_name}}</td>
                        <td>
                        	@if($user->super_admin == 1) 
                        		<span class="badge badge-success">Si</span> 
                        	@else 
                        		<span class="badge badge-info">No</span> 
                        	@endif
                        </td>
        				<td>
                            @if ($user->last_access)
                                {{ $user->last_access }}
                            @else
                                -
                            @endif
                        </td>
        				<td>
        					<a class="btn btn-warning btn-flat " href="{{ route('users.edit',['id' => $user->id]) }}"><i class="i-Pen-2"></i> Editar</a>
        					<button class="btn btn-danger btn-flat  delete-btn" data-toggle="modal" data-target="#delete-modal"  data-object="{{$user}}" data-fieldname="{{$user->person->name}} {{$user->person->last_name}}" data-message="Está seguro de eliminar el Usuario" data-route="{{ route('users.destroy',$user->id) }}"><i class="i-File-Trash"></i> Eliminar</button>
        				</td>
        			</tr>
        			@endforeach
            		
        		</tbody>
        	</table>
        </div>
    </div>

</div>
@endsection